### ISSUE TITLE
css variables in scss files not compiling map-get function

### ISSUE THREAD

**Issue by richs99** [failwyn/WebCompiler#13] opened 2021-11-18 09:29 UTC
### Installed product versions
- Visual Studio: Community 22
- This extension: [example 1.14.0]

### Description
map-get commands in scss files are not being replaced with values for css variables.

### Steps to recreate
1. put in scss file:

#test {
  --mainBackground: map-get($colors, 'red');
  background: map-get($colors, 'red');
}

2. Compile.

### Current behavior
When compiled, the background value will be correctly replaced with the red from the $colors array, but the --mainBackground variable does not:

#test {
  --mainBackground: map-get($colors, 'red');
  background: #FF0000;
}

### Expected behavior
The css variable should also have the value replaced.

**Comment by failwyn** [comment] 2021-11-18 11:28
This is not valid SASS syntax, see #4 for proper syntax.

Duplicate of #4, #11, and #12

**Closed by failwyn** 2021-11-18 11:28 UTC
